# Generated by Django 5.2.1 on 2026-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(max_length=30),
        ),
    ]
