# Generated by Django 5.2.1 on 2026-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
