# Generated by Django 5.2.1 on 2026-03-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0005_suggestedretailprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"ordering": ["-purchase_date"]},
        ),
    ]
