# Generated by Django 5.2.1 on 2026-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedretailprice',
            name='price_type',
            field=models.CharField(blank=True, choices=[('unit', 'Por unidad'), ('kg', 'Por kilogramo'), ('lb', 'Por libra')], default='unit', max_length=20, null=True),
        ),
    ]
