# Generated by Django 5.2.1 on 2026-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_rename_shipment_date_post_code_to_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
