# Generated by Django 5.2.1 on 2026-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_discount_price_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quality",
            field=models.CharField(default="segunda", max_length=30),
        ),
    ]
