# Generated by Django 5.2.1 on 2026-03-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "extra_price_quality",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "first_price_quality",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_per_unity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.unitofmeasure",
                    ),
                ),
            ],
        ),
    ]
