# Generated by Django 5.2.1 on 2026-03-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_productreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreference",
            name="variation",
            field=models.CharField(
                choices=[
                    ("STABLE", "Estable"),
                    ("WENT_UP", "Subío"),
                    ("WENT_DOWN", "Bajó"),
                ],
                default="STABLE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="productreference",
            name="weight",
            field=models.IntegerField(default=1),
        ),
    ]
