# Generated by Django 5.2.1 on 2026-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_productreference_variation_productreference_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreference",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="unity",
            field=models.CharField(
                choices=[
                    ("CANASTILLA", "CANASTILLA"),
                    ("MANOJO", "MANOJO"),
                    ("BULTO", "BULTO"),
                    ("CAJA", "CAJA"),
                    ("ATADOS", "ATADOS"),
                    ("DOCENA", "DOCENA"),
                    ("BOLSAS", "BOLSAS"),
                    ("GUACAL", "GUACAL"),
                    ("BANDEJA", "BANDEJA"),
                    ("ESTUCHE", "ESTUCHE"),
                    ("PONY", "PONY"),
                    ("TONELADA", "TONELADA"),
                    ("KG", "KG"),
                ],
                max_length=30,
            ),
        ),
    ]
