# Generated by Django 5.2.1 on 2026-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productreference_category_alter_unitofmeasure_unity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'sku']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['unity']},
        ),
    ]
