# Generated by Django 5.2.1 on 2026-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
